version: "3.2"
services:
  api:
    image: 'spring-testcontainers-image'
    ports:
    - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=containerized
    depends_on:
      - redis
  redis:
    container_name: redis-cache
    image: redis
    command: sh -c "rm -f /data/dump.rdb && redis-server"
    ports:
    - "6379:6379"
  db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Str0ngPassw0rd"
      ACCEPT_EULA: "Y"