springdoc:
  swagger-ui:
    path: /api-docs

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379

google-books-base-url: https://www.googleapis.com