springdoc:
  swagger-ui:
    path: /api-docs

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  redis:
    host: localhost
    port: 6379

google-books-base-url: https://www.googleapis.com